ALTER TABLE zBooks_borrowed
ADD CONSTRAINT ZBOOKS_BORROWER_USER_ID FOREIGN KEY (IDBORROWER) REFERENCES ZUSER (USER_ID);

ALTER TABLE zBooks_borrowed
ADD CONSTRAINT ZBOOKS_BORROWER_BOOK_ID FOREIGN KEY (IDBOOK) REFERENCES ZBOOKS (BOOK_ID);